project_name: kafta
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
    goarm:
      - '7'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/electric-saw/kafta/internal/version.version={{.Tag}}
      - -X github.com/electric-saw/kafta/internal/version.metadata={{.Branch}}
      - -X github.com/electric-saw/kafta/internal/version.gitCommit={{.ShortCommit}}
    main: ./cmd/kafta
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
