title: "Kafta"
description: "Modern, non-JVM command-line interface for managing Apache Kafka clusters"
baseurl: "/kafta"  # Adicione isso se for um projeto em repositório
url: "https://torresglauco.github.io"  # Mude para seu username
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author:
  name: "Glauco Torres"  # Mude para seu nome
social:
  name: "Kafta"
  links:
    - "https://github.com/torresglauco/kafta"  # URL correta do seu repo
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
